import React from 'react'
import AddTask from './AddTask'
// import Head from 'next/head';
export const metadata = {
  title: "ADD TASK - Work Manager",
  description: "Generated by create next app",
};

// facing issue for metadata

function AddTaskPage() {
  return (
    <>
    <AddTask/>
    </>
  )
}

export default AddTaskPage