import React from 'react'
import SignUpComp from './SignUp';

export const metadata = {
  title: "SIGN-UP - Work Manager",
  description: "Generated by create next app",
};

function SignUpPage() {
  return (
    <>
    <SignUpComp/>
    </>
  )
}

export default SignUpPage;